### ISSUE TITLE
Filter on product types and search

### ISSUE THREAD

**Issue by chrlofs** [dotkom/Nibble2#30]
In Nibble1 you could filter the products on the product type. This is not included in the new version and it is harder to locate the product I want to buy. Would also appreciate a search field with live update when typing.

**Comment by sardred** [comment]
Product filter has been implemented as of #36 
As the pull request notes, we decided not to add a search field because "[...] I think having to type in a query on an on-screen keyboard is more cumbersome and therefor (sic) doesn't really solve the problem."
We believe the alphabetical sorting (implemented in #10) makes intuitive enough to know _where_ the item you want is, it's just a matter of scrolling.
We're looking into adding different ordering, like ordering by item popularity, but no guarantee on that.
